//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizedText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        internal static string Account_ConfirmEmail_Error {
            get {
                return ResourceManager.GetString("Account_ConfirmEmail_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigado por confirmares o teu email..
        /// </summary>
        internal static string Account_ConfirmEmail_MainTitle {
            get {
                return ResourceManager.GetString("Account_ConfirmEmail_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vais ser redirecionado para o teu bilhete dentro de segundos..
        /// </summary>
        internal static string Account_ConfirmEmail_TicketRedirect {
            get {
                return ResourceManager.GetString("Account_ConfirmEmail_TicketRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Account_ResetPassword_btnReset_Text {
            get {
                return ResourceManager.GetString("Account_ResetPassword_btnReset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        internal static string Account_ResetPassword_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_ResetPassword_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your new password.
        /// </summary>
        internal static string Account_ResetPassword_MainTitle {
            get {
                return ResourceManager.GetString("Account_ResetPassword_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was changed sucessfully..
        /// </summary>
        internal static string Account_ResetPassword_SuccessMessage {
            get {
                return ResourceManager.GetString("Account_ResetPassword_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        internal static string Account_ResetPassword_tbConfirmPassword_CompareValidator_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_ResetPassword_tbConfirmPassword_CompareValidator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetir password.
        /// </summary>
        internal static string Account_ResetPassword_tbConfirmPassword_placeholder {
            get {
                return ResourceManager.GetString("Account_ResetPassword_tbConfirmPassword_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirm password field is required..
        /// </summary>
        internal static string Account_ResetPassword_tbConfirmPassword_Validator_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_ResetPassword_tbConfirmPassword_Validator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de email.
        /// </summary>
        internal static string Account_ResetPassword_tbEmail_placeholder {
            get {
                return ResourceManager.GetString("Account_ResetPassword_tbEmail_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email field is required..
        /// </summary>
        internal static string Account_ResetPassword_tbEmail_Validator_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_ResetPassword_tbEmail_Validator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova password.
        /// </summary>
        internal static string Account_ResetPassword_tbPassword_placeholder {
            get {
                return ResourceManager.GetString("Account_ResetPassword_tbPassword_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password field is required..
        /// </summary>
        internal static string Account_ResetPassword_tbPassword_Validator_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_ResetPassword_tbPassword_Validator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but this trip is no longer available..
        /// </summary>
        internal static string Calendar_BookingPanel_Booking_ErrorMessage {
            get {
                return ResourceManager.GetString("Calendar_BookingPanel_Booking_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoje.
        /// </summary>
        internal static string Calendar_CalendarHeader_btnToday_Text {
            get {
                return ResourceManager.GetString("Calendar_CalendarHeader_btnToday_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolhe o Destino e Origem da viagem.
        /// </summary>
        internal static string Calendar_CalendarPlaceholder_Text {
            get {
                return ResourceManager.GetString("Calendar_CalendarPlaceholder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocupação:.
        /// </summary>
        internal static string Calendar_CalendarTable_Footer_Ocup {
            get {
                return ResourceManager.GetString("Calendar_CalendarTable_Footer_Ocup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta.
        /// </summary>
        internal static string Calendar_CalendarTable_Footer_Ocup_High {
            get {
                return ResourceManager.GetString("Calendar_CalendarTable_Footer_Ocup_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baixa.
        /// </summary>
        internal static string Calendar_CalendarTable_Footer_Ocup_Low {
            get {
                return ResourceManager.GetString("Calendar_CalendarTable_Footer_Ocup_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Média.
        /// </summary>
        internal static string Calendar_CalendarTable_Footer_Ocup_Med {
            get {
                return ResourceManager.GetString("Calendar_CalendarTable_Footer_Ocup_Med", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string Calendar_CalendarTable_Header_Weekdays_Fri {
            get {
                return ResourceManager.GetString("Calendar_CalendarTable_Header_Weekdays_Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seg.
        /// </summary>
        internal static string Calendar_CalendarTable_Header_Weekdays_Mon {
            get {
                return ResourceManager.GetString("Calendar_CalendarTable_Header_Weekdays_Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sab.
        /// </summary>
        internal static string Calendar_CalendarTable_Header_Weekdays_Sat {
            get {
                return ResourceManager.GetString("Calendar_CalendarTable_Header_Weekdays_Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dom.
        /// </summary>
        internal static string Calendar_CalendarTable_Header_Weekdays_Sun {
            get {
                return ResourceManager.GetString("Calendar_CalendarTable_Header_Weekdays_Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qui.
        /// </summary>
        internal static string Calendar_CalendarTable_Header_Weekdays_Thu {
            get {
                return ResourceManager.GetString("Calendar_CalendarTable_Header_Weekdays_Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ter.
        /// </summary>
        internal static string Calendar_CalendarTable_Header_Weekdays_Tue {
            get {
                return ResourceManager.GetString("Calendar_CalendarTable_Header_Weekdays_Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qua.
        /// </summary>
        internal static string Calendar_CalendarTable_Header_Weekdays_Wed {
            get {
                return ResourceManager.GetString("Calendar_CalendarTable_Header_Weekdays_Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esgotado.
        /// </summary>
        internal static string Calendar_Controls_CalendarTable_DayInfoText_BLACK {
            get {
                return ResourceManager.GetString("Calendar_Controls_CalendarTable_DayInfoText_BLACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quase cheio.
        /// </summary>
        internal static string Calendar_Controls_CalendarTable_DayInfoText_RED {
            get {
                return ResourceManager.GetString("Calendar_Controls_CalendarTable_DayInfoText_RED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino.
        /// </summary>
        internal static string Calendar_Controls_Popover_Header_DestinationLabel {
            get {
                return ResourceManager.GetString("Calendar_Controls_Popover_Header_DestinationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origem.
        /// </summary>
        internal static string Calendar_Controls_Popover_Header_OriginLabel {
            get {
                return ResourceManager.GetString("Calendar_Controls_Popover_Header_OriginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragem.
        /// </summary>
        internal static string Calendar_Header_APDropdown_Label {
            get {
                return ResourceManager.GetString("Calendar_Header_APDropdown_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolher paragem.
        /// </summary>
        internal static string Calendar_Header_APDropdown_SelectionPrompt {
            get {
                return ResourceManager.GetString("Calendar_Header_APDropdown_SelectionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ida e volta.
        /// </summary>
        internal static string Calendar_Header_cbReturnTrip_Label {
            get {
                return ResourceManager.GetString("Calendar_Header_cbReturnTrip_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino.
        /// </summary>
        internal static string Calendar_Header_DestinationDropdown_Label {
            get {
                return ResourceManager.GetString("Calendar_Header_DestinationDropdown_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolher destino.
        /// </summary>
        internal static string Calendar_Header_DestinationDropdown_SelectionPrompt {
            get {
                return ResourceManager.GetString("Calendar_Header_DestinationDropdown_SelectionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origem.
        /// </summary>
        internal static string Calendar_Header_OriginDropdown_Label {
            get {
                return ResourceManager.GetString("Calendar_Header_OriginDropdown_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolher origem.
        /// </summary>
        internal static string Calendar_Header_OriginDropdown_SelectionPrompt {
            get {
                return ResourceManager.GetString("Calendar_Header_OriginDropdown_SelectionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugares.
        /// </summary>
        internal static string Calendar_Header_SeatsDropdown_Label {
            get {
                return ResourceManager.GetString("Calendar_Header_SeatsDropdown_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string Controls_Forgot_btnForgot_Text {
            get {
                return ResourceManager.GetString("Controls_Forgot_btnForgot_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoyoloop login.
        /// </summary>
        internal static string Controls_Forgot_MainTitle {
            get {
                return ResourceManager.GetString("Controls_Forgot_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ainda não tens conta?.
        /// </summary>
        internal static string Controls_Forgot_NoAccount {
            get {
                return ResourceManager.GetString("Controls_Forgot_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registar.
        /// </summary>
        internal static string Controls_Forgot_RegisterLink {
            get {
                return ResourceManager.GetString("Controls_Forgot_RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user does not exist..
        /// </summary>
        internal static string Controls_Forgot_ResultMessage_Failure {
            get {
                return ResourceManager.GetString("Controls_Forgot_ResultMessage_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        internal static string Controls_Forgot_ResultMessage_Success {
            get {
                return ResourceManager.GetString("Controls_Forgot_ResultMessage_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueceste a password?.
        /// </summary>
        internal static string Controls_Forgot_SubTitle_1 {
            get {
                return ResourceManager.GetString("Controls_Forgot_SubTitle_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduz o teu email.
        /// </summary>
        internal static string Controls_Forgot_SubTitle_2 {
            get {
                return ResourceManager.GetString("Controls_Forgot_SubTitle_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de email.
        /// </summary>
        internal static string Controls_Forgot_tbForgotEmail_placeholder {
            get {
                return ResourceManager.GetString("Controls_Forgot_tbForgotEmail_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email field is required..
        /// </summary>
        internal static string Controls_Forgot_tbForgotEmail_Validator_ErrorMessage {
            get {
                return ResourceManager.GetString("Controls_Forgot_tbForgotEmail_Validator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        internal static string Controls_Login_btnLogin_Text {
            get {
                return ResourceManager.GetString("Controls_Login_btnLogin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar-me da &lt;br&gt;password.
        /// </summary>
        internal static string Controls_Login_cbRememberMe {
            get {
                return ResourceManager.GetString("Controls_Login_cbRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueci-me da password.
        /// </summary>
        internal static string Controls_Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Controls_Login_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        internal static string Controls_Login_LoginMessageFailure_Text {
            get {
                return ResourceManager.GetString("Controls_Login_LoginMessageFailure_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login sucessful.
        /// </summary>
        internal static string Controls_Login_LoginMessageSucess_Text {
            get {
                return ResourceManager.GetString("Controls_Login_LoginMessageSucess_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Controls_Login_LoginOr {
            get {
                return ResourceManager.GetString("Controls_Login_LoginOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoyoloop Login.
        /// </summary>
        internal static string Controls_Login_MainTitle {
            get {
                return ResourceManager.GetString("Controls_Login_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ainda não tens conta?.
        /// </summary>
        internal static string Controls_Login_NoAccount {
            get {
                return ResourceManager.GetString("Controls_Login_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registar.
        /// </summary>
        internal static string Controls_Login_RegisterLink {
            get {
                return ResourceManager.GetString("Controls_Login_RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de email.
        /// </summary>
        internal static string Controls_Login_tbLoginEmail_placeholder {
            get {
                return ResourceManager.GetString("Controls_Login_tbLoginEmail_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email field is required..
        /// </summary>
        internal static string Controls_Login_tbLoginEmail_Validator_ErrorMessage {
            get {
                return ResourceManager.GetString("Controls_Login_tbLoginEmail_Validator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Controls_Login_tbLoginPassword_placeholder {
            get {
                return ResourceManager.GetString("Controls_Login_tbLoginPassword_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password field is required..
        /// </summary>
        internal static string Controls_Login_tbLoginPassword_Validator_ErrorMessage {
            get {
                return ResourceManager.GetString("Controls_Login_tbLoginPassword_Validator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regista-te com o teu email.
        /// </summary>
        internal static string Controls_Login_WithEmail {
            get {
                return ResourceManager.GetString("Controls_Login_WithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com Facebook.
        /// </summary>
        internal static string Controls_Login_WithFacebook {
            get {
                return ResourceManager.GetString("Controls_Login_WithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com Google.
        /// </summary>
        internal static string Controls_Login_WithGoogle {
            get {
                return ResourceManager.GetString("Controls_Login_WithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        internal static string Controls_Register_btnRegisterContinue_Text {
            get {
                return ResourceManager.GetString("Controls_Register_btnRegisterContinue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quero receber campanhas&lt;br&gt;promocionais da Yoyoloop.
        /// </summary>
        internal static string Controls_Register_cbRegisterCampaigns {
            get {
                return ResourceManager.GetString("Controls_Register_cbRegisterCampaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já tens conta?.
        /// </summary>
        internal static string Controls_Register_HaveAccount {
            get {
                return ResourceManager.GetString("Controls_Register_HaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fazer login.
        /// </summary>
        internal static string Controls_Register_LoginLink {
            get {
                return ResourceManager.GetString("Controls_Register_LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoyoloop login.
        /// </summary>
        internal static string Controls_Register_MainTitle {
            get {
                return ResourceManager.GetString("Controls_Register_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro.
        /// </summary>
        internal static string Controls_Register_RegisterMessage_Failure {
            get {
                return ResourceManager.GetString("Controls_Register_RegisterMessage_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Controls_Register_RegisterOr {
            get {
                return ResourceManager.GetString("Controls_Register_RegisterOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email and confirmation email do not match..
        /// </summary>
        internal static string Controls_Register_tbRegisterConfirmEmail_CompareValidator_ErrorMessage {
            get {
                return ResourceManager.GetString("Controls_Register_tbRegisterConfirmEmail_CompareValidator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetir Endereço de email.
        /// </summary>
        internal static string Controls_Register_tbRegisterConfirmEmail_placeholder {
            get {
                return ResourceManager.GetString("Controls_Register_tbRegisterConfirmEmail_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirm email field is required..
        /// </summary>
        internal static string Controls_Register_tbRegisterConfirmEmail_Validator_ErrorMessage {
            get {
                return ResourceManager.GetString("Controls_Register_tbRegisterConfirmEmail_Validator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        internal static string Controls_Register_tbRegisterConfirmPassword_CompareValidator_ErrorMessage {
            get {
                return ResourceManager.GetString("Controls_Register_tbRegisterConfirmPassword_CompareValidator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetir password.
        /// </summary>
        internal static string Controls_Register_tbRegisterConfirmPassword_placeholder {
            get {
                return ResourceManager.GetString("Controls_Register_tbRegisterConfirmPassword_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirm password field is required..
        /// </summary>
        internal static string Controls_Register_tbRegisterConfirmPassword_Validator_ErrorMessage {
            get {
                return ResourceManager.GetString("Controls_Register_tbRegisterConfirmPassword_Validator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de email.
        /// </summary>
        internal static string Controls_Register_tbRegisterEmail_placeholder {
            get {
                return ResourceManager.GetString("Controls_Register_tbRegisterEmail_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email field is required..
        /// </summary>
        internal static string Controls_Register_tbRegisterEmail_Validator_ErrorMessage {
            get {
                return ResourceManager.GetString("Controls_Register_tbRegisterEmail_Validator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string Controls_Register_tbRegisterName_placeholder {
            get {
                return ResourceManager.GetString("Controls_Register_tbRegisterName_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name field is required..
        /// </summary>
        internal static string Controls_Register_tbRegisterName_Validator_ErrorMessage {
            get {
                return ResourceManager.GetString("Controls_Register_tbRegisterName_Validator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Controls_Register_tbRegisterPassword_placeholder {
            get {
                return ResourceManager.GetString("Controls_Register_tbRegisterPassword_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password field is required..
        /// </summary>
        internal static string Controls_Register_tbRegisterPassword_Validator_ErrorMessage {
            get {
                return ResourceManager.GetString("Controls_Register_tbRegisterPassword_Validator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para receberes o teu bilhete,&lt;br&gt;primeiro precisamos dos teus dados.
        /// </summary>
        internal static string Controls_Register_WithEmail {
            get {
                return ResourceManager.GetString("Controls_Register_WithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com Facebook.
        /// </summary>
        internal static string Controls_Register_WithFacebook {
            get {
                return ResourceManager.GetString("Controls_Register_WithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com Google.
        /// </summary>
        internal static string Controls_Register_WithGoogle {
            get {
                return ResourceManager.GetString("Controls_Register_WithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lugar.
        /// </summary>
        internal static string General_Seat {
            get {
                return ResourceManager.GetString("General_Seat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lugares.
        /// </summary>
        internal static string General_Seats {
            get {
                return ResourceManager.GetString("General_Seats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vê passar os autocarros e apanha boleia à porta de casa.
        /// </summary>
        internal static string HomePage_MainTitle {
            get {
                return ResourceManager.GetString("HomePage_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não encontras a tua cidade?.
        /// </summary>
        internal static string HomePage_PopularLoops_CantFind {
            get {
                return ResourceManager.GetString("HomePage_PopularLoops_CantFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidade.
        /// </summary>
        internal static string HomePage_PopularLoops_Features_Capacity {
            get {
                return ResourceManager.GetString("HomePage_PopularLoops_Features_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duracao.
        /// </summary>
        internal static string HomePage_PopularLoops_Features_Duration {
            get {
                return ResourceManager.GetString("HomePage_PopularLoops_Features_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grátis.
        /// </summary>
        internal static string HomePage_PopularLoops_Features_Free {
            get {
                return ResourceManager.GetString("HomePage_PopularLoops_Features_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço.
        /// </summary>
        internal static string HomePage_PopularLoops_Features_Price {
            get {
                return ResourceManager.GetString("HomePage_PopularLoops_Features_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        internal static string HomePage_PopularLoops_Features_Price_From {
            get {
                return ResourceManager.GetString("HomePage_PopularLoops_Features_Price_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugares.
        /// </summary>
        internal static string HomePage_PopularLoops_Features_Seats {
            get {
                return ResourceManager.GetString("HomePage_PopularLoops_Features_Seats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservar.
        /// </summary>
        internal static string HomePage_PopularLoops_ReserveLink {
            get {
                return ResourceManager.GetString("HomePage_PopularLoops_ReserveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver todos.
        /// </summary>
        internal static string HomePage_PopularLoops_SeeAll_Link {
            get {
                return ResourceManager.GetString("HomePage_PopularLoops_SeeAll_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugere um loop.
        /// </summary>
        internal static string HomePage_PopularLoops_SuggestLink {
            get {
                return ResourceManager.GetString("HomePage_PopularLoops_SuggestLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loops Populares.
        /// </summary>
        internal static string HomePage_PopularLoops_Title {
            get {
                return ResourceManager.GetString("HomePage_PopularLoops_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserva o teu lugar num transfer de sete lugares conduzido por um motorista profissional e aproveita uma viagem sem paragens, com wifi a bordo e a preço de autocarro..
        /// </summary>
        internal static string HomePage_SubTitle {
            get {
                return ResourceManager.GetString("HomePage_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não encontras a tua cidade?.
        /// </summary>
        internal static string HomePage_SuggestLink {
            get {
                return ResourceManager.GetString("HomePage_SuggestLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string HomePage_SuggestLoop_btnSuggestSend {
            get {
                return ResourceManager.GetString("HomePage_SuggestLoop_btnSuggestSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não encontras a tua cidade?.
        /// </summary>
        internal static string HomePage_SuggestLoop_MainTitle {
            get {
                return ResourceManager.GetString("HomePage_SuggestLoop_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tua sugestão foi enviada.
        /// </summary>
        internal static string HomePage_SuggestLoop_SuggestSend_Message {
            get {
                return ResourceManager.GetString("HomePage_SuggestLoop_SuggestSend_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tua sugestão.
        /// </summary>
        internal static string HomePage_SuggestLoop_tbSuggestBody_placeholder {
            get {
                return ResourceManager.GetString("HomePage_SuggestLoop_tbSuggestBody_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O teu endereço de email.
        /// </summary>
        internal static string HomePage_SuggestLoop_tbSuggestEmail_placeholder {
            get {
                return ResourceManager.GetString("HomePage_SuggestLoop_tbSuggestEmail_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queres que a Yoyoloop te dê boleia até à tua cidade?&lt;br&gt;Sugere um loop e fica atento às novidades!.
        /// </summary>
        internal static string HomePage_SuggestLoop_Text {
            get {
                return ResourceManager.GetString("HomePage_SuggestLoop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.
        /// </summary>
        internal static string HomePage_WhereToCard_Location_And {
            get {
                return ResourceManager.GetString("HomePage_WhereToCard_Location_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De.
        /// </summary>
        internal static string HomePage_WhereToCard_Location_From {
            get {
                return ResourceManager.GetString("HomePage_WhereToCard_Location_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        internal static string HomePage_WhereToCard_Price_From {
            get {
                return ResourceManager.GetString("HomePage_WhereToCard_Price_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservar.
        /// </summary>
        internal static string HomePage_WhereToCard_ReserveLink {
            get {
                return ResourceManager.GetString("HomePage_WhereToCard_ReserveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos os dias.
        /// </summary>
        internal static string HomePage_WhereToCard_When_Everyday {
            get {
                return ResourceManager.GetString("HomePage_WhereToCard_When_Everyday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para onde queres ir?.
        /// </summary>
        internal static string HomePage_WhereToGo {
            get {
                return ResourceManager.GetString("HomePage_WhereToGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por um loop, chegas a pagar 75% menos do que se levasses o teu próprio carro e exactamente o mesmo do que pagarias por ir de autocarro ou outros transportes — e ainda tens uma viagem muito mais confortável e menos desgastante..
        /// </summary>
        internal static string HomePage_Why_Card_Accessible_Content {
            get {
                return ResourceManager.GetString("HomePage_Why_Card_Accessible_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menos desgaste,&lt;br&gt;mais na carteira.
        /// </summary>
        internal static string HomePage_Why_Card_Accessible_SubTitle {
            get {
                return ResourceManager.GetString("HomePage_Why_Card_Accessible_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acessível.
        /// </summary>
        internal static string HomePage_Why_Card_Accessible_Title {
            get {
                return ResourceManager.GetString("HomePage_Why_Card_Accessible_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Além de contar com partidas frequentes, a Yoyoloop vai pôr-te e buscar-te a pontos estratégicos da cidade, como estações de metro, supermercados, largos dos centros urbanos e as principais zonas de escritórios de Lisboa — e ainda te oferece wifi a bordo..
        /// </summary>
        internal static string HomePage_Why_Card_Convenient_Content {
            get {
                return ResourceManager.GetString("HomePage_Why_Card_Convenient_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up e drop off&lt;br&gt;convenientes.
        /// </summary>
        internal static string HomePage_Why_Card_Convenient_SubTitle {
            get {
                return ResourceManager.GetString("HomePage_Why_Card_Convenient_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conveniente.
        /// </summary>
        internal static string HomePage_Why_Card_Convenient_Title {
            get {
                return ResourceManager.GetString("HomePage_Why_Card_Convenient_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um motorista profissional dá-te boleia com locais e horas de partida fixas. Basta escolheres o teu ponto de saída, reservar a tua viagem, e sentares-te no teu lugar à hora marcada..
        /// </summary>
        internal static string HomePage_Why_Card_Reliable_Content {
            get {
                return ResourceManager.GetString("HomePage_Why_Card_Reliable_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar marcado,&lt;br&gt;à hora marcada.
        /// </summary>
        internal static string HomePage_Why_Card_Reliable_SubTitle {
            get {
                return ResourceManager.GetString("HomePage_Why_Card_Reliable_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiável.
        /// </summary>
        internal static string HomePage_Why_Card_Reliable_Title {
            get {
                return ResourceManager.GetString("HomePage_Why_Card_Reliable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas as nossas viagens são feitas em veículos de sete lugares. Não só tiramos mais carros da estrada, como também ajudamos a reduzir a pegada de carbono..
        /// </summary>
        internal static string HomePage_Why_Card_Sustainable_Content {
            get {
                return ResourceManager.GetString("HomePage_Why_Card_Sustainable_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menos carros,&lt;br&gt;mais cidade.
        /// </summary>
        internal static string HomePage_Why_Card_Sustainable_SubTitle {
            get {
                return ResourceManager.GetString("HomePage_Why_Card_Sustainable_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustentável.
        /// </summary>
        internal static string HomePage_Why_Card_Sustainable_Title {
            get {
                return ResourceManager.GetString("HomePage_Why_Card_Sustainable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porquê apanhar boleia de um transfer da Yoyoloop?.
        /// </summary>
        internal static string HomePage_Why_Title {
            get {
                return ResourceManager.GetString("HomePage_Why_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O único transporte ponto a ponto alternativo aos autocarros,&lt;br&gt; comboios e boleias tradicionais.
        /// </summary>
        internal static string HomePage_Yoyoloop_MainDescription {
            get {
                return ResourceManager.GetString("HomePage_Yoyoloop_MainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O autocarro é demorado, há falta de comboios directos, nem sempre há boleias e não compensa levar o carro vazio. Com um transfer da Yoyoloop, podes ir para Lisboa, Cascais, Leiria e Coimbra sem paragens e a preço de autocarro..
        /// </summary>
        internal static string HomePage_Yoyoloop_SubDescription {
            get {
                return ResourceManager.GetString("HomePage_Yoyoloop_SubDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation of Anti-XSRF token failed..
        /// </summary>
        internal static string SiteMaster_Errors_AntiXSRF {
            get {
                return ResourceManager.GetString("SiteMaster_Errors_AntiXSRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinos.
        /// </summary>
        internal static string SiteMaster_Footer_Destinos {
            get {
                return ResourceManager.GetString("SiteMaster_Footer_Destinos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês.
        /// </summary>
        internal static string SiteMaster_Footer_Language_English {
            get {
                return ResourceManager.GetString("SiteMaster_Footer_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        internal static string SiteMaster_Footer_Language_Portuguese {
            get {
                return ResourceManager.GetString("SiteMaster_Footer_Language_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loops.
        /// </summary>
        internal static string SiteMaster_Footer_Loops {
            get {
                return ResourceManager.GetString("SiteMaster_Footer_Loops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politica de privacidade.
        /// </summary>
        internal static string SiteMaster_Footer_Privacy {
            get {
                return ResourceManager.GetString("SiteMaster_Footer_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termos e Condiçōes.
        /// </summary>
        internal static string SiteMaster_Footer_Terms {
            get {
                return ResourceManager.GetString("SiteMaster_Footer_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre nós.
        /// </summary>
        internal static string SiteMaster_Footer_Yoyoloop_About {
            get {
                return ResourceManager.GetString("SiteMaster_Footer_Yoyoloop_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        internal static string SiteMaster_Footer_Yoyoloop_Contact {
            get {
                return ResourceManager.GetString("SiteMaster_Footer_Yoyoloop_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajuda.
        /// </summary>
        internal static string SiteMaster_Footer_Yoyoloop_Help {
            get {
                return ResourceManager.GetString("SiteMaster_Footer_Yoyoloop_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como funciona.
        /// </summary>
        internal static string SiteMaster_Footer_Yoyoloop_HowTo {
            get {
                return ResourceManager.GetString("SiteMaster_Footer_Yoyoloop_HowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinos.
        /// </summary>
        internal static string SiteMaster_NavBar_Destinations {
            get {
                return ResourceManager.GetString("SiteMaster_NavBar_Destinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loops &amp; horarios.
        /// </summary>
        internal static string SiteMaster_NavBar_LoopsAndSchedules {
            get {
                return ResourceManager.GetString("SiteMaster_NavBar_LoopsAndSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As minhas viagens.
        /// </summary>
        internal static string SiteMaster_NavBar_MyTrips {
            get {
                return ResourceManager.GetString("SiteMaster_NavBar_MyTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registar/Entrar.
        /// </summary>
        internal static string SiteMaster_NavBar_RegisterLogin {
            get {
                return ResourceManager.GetString("SiteMaster_NavBar_RegisterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes de Faturação.
        /// </summary>
        internal static string SiteMaster_ProfileMenu_Billing {
            get {
                return ResourceManager.GetString("SiteMaster_ProfileMenu_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convidar amigos.
        /// </summary>
        internal static string SiteMaster_ProfileMenu_Invite {
            get {
                return ResourceManager.GetString("SiteMaster_ProfileMenu_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string SiteMaster_ProfileMenu_Logout {
            get {
                return ResourceManager.GetString("SiteMaster_ProfileMenu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Meu Perfil.
        /// </summary>
        internal static string SiteMaster_ProfileMenu_Profile {
            get {
                return ResourceManager.GetString("SiteMaster_ProfileMenu_Profile", resourceCulture);
            }
        }
    }
}
