//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizedText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        internal static string Controls_Login_btnLogin_Text {
            get {
                return ResourceManager.GetString("Controls_Login_btnLogin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar-me da &lt;br&gt;password.
        /// </summary>
        internal static string Controls_Login_cbRememberMe {
            get {
                return ResourceManager.GetString("Controls_Login_cbRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueci-me da password.
        /// </summary>
        internal static string Controls_Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Controls_Login_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        internal static string Controls_Login_LoginMessageFailure_Text {
            get {
                return ResourceManager.GetString("Controls_Login_LoginMessageFailure_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login sucessful.
        /// </summary>
        internal static string Controls_Login_LoginMessageSucess_Text {
            get {
                return ResourceManager.GetString("Controls_Login_LoginMessageSucess_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Controls_Login_LoginOr {
            get {
                return ResourceManager.GetString("Controls_Login_LoginOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoyoloop Login.
        /// </summary>
        internal static string Controls_Login_MainTitle {
            get {
                return ResourceManager.GetString("Controls_Login_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ainda não tens conta?.
        /// </summary>
        internal static string Controls_Login_NoAccount {
            get {
                return ResourceManager.GetString("Controls_Login_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registar.
        /// </summary>
        internal static string Controls_Login_RegisterLink {
            get {
                return ResourceManager.GetString("Controls_Login_RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de email.
        /// </summary>
        internal static string Controls_Login_tbLoginEmail_placeholder {
            get {
                return ResourceManager.GetString("Controls_Login_tbLoginEmail_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email field is required..
        /// </summary>
        internal static string Controls_Login_tbLoginEmail_Validator_ErrorMessage {
            get {
                return ResourceManager.GetString("Controls_Login_tbLoginEmail_Validator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Controls_Login_tbLoginPassword_placeholder {
            get {
                return ResourceManager.GetString("Controls_Login_tbLoginPassword_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password field is required..
        /// </summary>
        internal static string Controls_Login_tbLoginPassword_Validator_ErrorMessage {
            get {
                return ResourceManager.GetString("Controls_Login_tbLoginPassword_Validator_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regista-te com o teu email.
        /// </summary>
        internal static string Controls_Login_WithEmail {
            get {
                return ResourceManager.GetString("Controls_Login_WithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com Facebook.
        /// </summary>
        internal static string Controls_Login_WithFacebook {
            get {
                return ResourceManager.GetString("Controls_Login_WithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com Google.
        /// </summary>
        internal static string Controls_Login_WithGoogle {
            get {
                return ResourceManager.GetString("Controls_Login_WithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinos.
        /// </summary>
        internal static string SiteMaster_NavBar_Destinations {
            get {
                return ResourceManager.GetString("SiteMaster_NavBar_Destinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loops &amp; horarios.
        /// </summary>
        internal static string SiteMaster_NavBar_LoopsAndSchedules {
            get {
                return ResourceManager.GetString("SiteMaster_NavBar_LoopsAndSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As minhas viagens.
        /// </summary>
        internal static string SiteMaster_NavBar_MyTrips {
            get {
                return ResourceManager.GetString("SiteMaster_NavBar_MyTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registar/Entrar.
        /// </summary>
        internal static string SiteMaster_NavBar_RegisterLogin {
            get {
                return ResourceManager.GetString("SiteMaster_NavBar_RegisterLogin", resourceCulture);
            }
        }
    }
}
