// <auto-generated />
namespace MVP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BookingPromocodeToString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookingPromocodeToString));
        
        string IMigrationMetadata.Id
        {
            get { return "201809100548466_Booking-Promocode-To-String"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
